apiVersion: v1
kind: ServiceAccount
metadata:
  name: contaxy

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contaxy
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "create", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "update", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "create", "delete", "update"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contaxy
subjects:
  - kind: ServiceAccount
    name: contaxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contaxy
