version: "3.3"
services:
  # The main ML Lab backend container that serves as entrypoint for all traffic
  # Contains the contaxy server and hosts the ML Lab web app
  ml-lab-backend:
    image: ghcr.io/sap/machine-learning-lab/lab-backend:0.0.22
    container_name: ml-lab-backend
    privileged: true # Required for accessing the docker socket
    ports:
      - "30010:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - JWT_TOKEN_SECRET=please-change-this-secret
      - SYSTEM_NAMESPACE=pylab
#      - SERVICE_SSL_ENABLED=true
      - CONTAXY_HOST=localhost:30010
#      - OIDC_AUTH_ENABLED=True
#      - OIDC_AUTH_URL=
#      - OIDC_TOKEN_URL=
#      - OIDC_CLIENT_ID=
#      - OIDC_CLIENT_SECRET=
      - POSTGRES_CONNECTION_URI=postgresql://postgres:postgres-password-change-me@postgres:5432/postgres
      - S3_ENDPOINT=s3:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minio-password-change-me
      - USER_REGISTRATION_ENABLED=True
      - CONTAXY_API_ENDPOINT=http://ml-lab-backend:8080/api
      - BACKEND_CORS_ORIGINS=http://localhost:3000
      - DEBUG=False
      - WEB_CONCURRENCY=1
      - JWT_TOKEN_EXPIRY_MINUTES=15 # 15 minutes
      - SERVICE_IDLE_CHECK_INTERVAL=1200 # 20 minutes
    depends_on:
      - postgres
      - s3
#    secrets:
#      - source: ssl_cert
#        target: /run/secrets/cert.crt
#      - source: ssl_key
#        target: /run/secrets/cert.key

  # Initialization container that calls the /system/initialize endpoint and thereby creates the default admin user
  ml-lab-backend-setup:
    image: curlimages/curl:7.75.0
    entrypoint:
      ["sh", "-c", "sleep 10 && curl -v -X POST http://ml-lab-backend:8080/api/system/initialize"]
    restart: "no"
    depends_on:
      - ml-lab-backend

  # Postgres database used by the contaxy server in the ML Lab backend
  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-password-change-me
    ports:
      - "127.0.0.1:30011:5432"
    volumes:
      - lab-postgres-data:/var/lib/postgresql/data

  # Web interface to access postgres DB
  # (ATTENTION: uncommenting gives access to the DB without authentication)
  # pgweb:
  #   container_name: pgweb
  #   restart: always
  #   image: sosedoff/pgweb
  #   # ports:
  #   #   - "30012:8081"
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres-password-change-me@postgres:5432/postgres?sslmode=disable
  #   depends_on:
  #     - postgres

  # Minio object storage used by the contaxy server in the ML Lab backend
  s3:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    command: server /data/data{1...4}
    ports:
        - "127.0.0.1:30013:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minio-password-change-me
    volumes:
      - lab-s3-data:/data

  # Start all ML Lab components. Each component is a contaxy extension.
  # Due to the specified name and labels they will be automatically picked up by the ML Lab backend.

  # Workspace manager that allows users to spawn their machine learning workspaces
  lab-workspace-manager:
    container_name: pylab-p-ctxy-global-s-workspace-manager
    image: ghcr.io/sap/machine-learning-lab/lab-workspace-manager:0.0.22
    environment:
      - CONTAXY_API_ENDPOINT=http://ml-lab-backend:8080/api
      - CONTAXY_DEPLOYMENT_NAME=pylab-p-ctxy-global-s-workspace-manager
      - CONTAXY_SERVICE_URL=/projects/ctxy-global/services/pylab-p-ctxy-global-s-workspace-manager/access/8080
      - WORKSPACE_MAX_MEMORY_MB=1024
      - WORKSPACE_MAX_CPUS=1
    labels:
      ctxy.deploymentType: "extension"
      ctxy.deploymentName: "pylab-p-ctxy-global-s-workspace-manager"
      ctxy.displayName: "Workspaces"
      ctxy.endpoints: "8080"
      ctxy.namespace: "pylab"
      ctxy.projectName: "ctxy-global"
      ctxy.extensionType: "global-extension"
      ctxy.icon: "code"
      ctxy.ui_extension_endpoint: "8080/app#/users/{env.userId}/workspace"
      ctxy.api_extension_endpoint: "8080/api"
      display_priority: 95

  # MLflow integration for experiment tracking
  lab-mlflow-manager:
    container_name: pylab-p-ctxy-global-s-lab-mlflow-manager
    image: ghcr.io/sap/machine-learning-lab/lab-mlflow-manager:0.0.22
    environment:
      - CONTAXY_API_ENDPOINT=http://ml-lab-backend:8080/api
      - CONTAXY_DEPLOYMENT_NAME=pylab-p-ctxy-global-s-mlflow
      - CONTAXY_SERVICE_URL=/projects/ctxy-global/services/pylab-p-ctxy-global-s-mlflow/access/8080
      - MLFLOW_SERVER_IMAGE=ghcr.io/sap/machine-learning-lab/lab-mlflow-server:0.0.22
      - MLFLOW_SERVER_IDLE_TIMEOUT=86400 # 24 hours
    labels:
      ctxy.deploymentType: "extension"
      ctxy.deploymentName: "pylab-p-ctxy-global-s-lab-mlflow-manager"
      ctxy.displayName: "MLflow Experiments"
      ctxy.endpoints: "8080"
      ctxy.namespace: "pylab"
      ctxy.projectName: "ctxy-global"
      ctxy.extensionType: "global-extension"
      ctxy.icon: "science"
      ctxy.ui_extension_endpoint: "8080/app#/mlflow-server"
      ctxy.api_extension_endpoint: "8080/api"
      display_priority: 95

#secrets:
#  ssl_cert:
#    file: /etc/ssl/certs/mllab-cert.crt
#  ssl_key:
#    file: /etc/ssl/certs/mllab-cert.key
volumes:
  lab-postgres-data: {}
  lab-s3-data: {}
